spring:
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/${DB_NAME:gamescoreboard}
    username: ${DB_USERNAME:gamescoreboard}
    password: ${DB_PASSWORD:password}
  application:
    name: game-score-desk
application:
  secretKey: ${SECRET_KEY:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9}
